package sportsell;
// Generated Oct 30, 2016 5:24:41 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer pid;
     private String pteam;
     private String psize;
     private String pcolor;
     private double pprice;
     private int pamount;

    public Product() {
    }

    public Product(String pteam, String psize, String pcolor, double pprice, int pamount) {
       this.pteam = pteam;
       this.psize = psize;
       this.pcolor = pcolor;
       this.pprice = pprice;
       this.pamount = pamount;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getPteam() {
        return this.pteam;
    }
    
    public void setPteam(String pteam) {
        this.pteam = pteam;
    }
    public String getPsize() {
        return this.psize;
    }
    
    public void setPsize(String psize) {
        this.psize = psize;
    }
    public String getPcolor() {
        return this.pcolor;
    }
    
    public void setPcolor(String pcolor) {
        this.pcolor = pcolor;
    }
    public double getPprice() {
        return this.pprice;
    }
    
    public void setPprice(double pprice) {
        this.pprice = pprice;
    }
    public int getPamount() {
        return this.pamount;
    }
    
    public void setPamount(int pamount) {
        this.pamount = pamount;
    }




}


